[package]
name = "devu"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Simple raylib-based game engine for Rust"
repository = "https://github.com/Celebro228/devu"
documentation = "https://docs.rs/devu"
keywords = ["gamedev", "webassembly", "3d", "graphics"]
categories = ["game-development", "graphics", "rendering"]
authors = ["Celebro228"]


[features]
multi_threaded = ["bevy_ecs/multi_threaded"]


[dependencies]
bevy_ecs = { version = "0.18.1", default-features = false, features = ["std"] }
bevy_app = { version = "0.18.1", default-features = false, features = ["std"] }
glam = "0.30.10"
linkme = "0.3.35"
devu_macro = { path = "./devu_macro", version = "*" }
num-traits = "0.2.19"


# Release mod
[profile.release]
lto = true
panic = "abort"
debug = false
opt-level = 3
overflow-checks = false
debug-assertions = false
incremental = false
rpath = false
codegen-units = 1
strip = true

[profile.release.package."*"]
opt-level = 3
