[package]
name = "devu_macro"
version = "0.2.0"
edition = "2024"
description = "A fast, minimal, and ergonomic entity-component-system library"
authors = ["Celebro"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Celebro228/devu"
keywords = ["ecs", "entity"]
categories = ["data-structures", "game-engines"]

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
